# Generated by Django 5.2.7 on 2025-11-02 21:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('training', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('val_accuracy', models.FloatField(blank=True, null=True)),
                ('epochs', models.IntegerField(default=10)),
                ('training_progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predictions/')),
                ('result', models.CharField(max_length=10)),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trained_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='classifier.trainedmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cats', 'Cats'), ('dogs', 'Dogs')], max_length=10)),
                ('image', models.ImageField(upload_to='training_data/')),
                ('is_validation', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('trained_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='classifier.trainedmodel')),
            ],
            options={
                'ordering': ['category', '-uploaded_at'],
            },
        ),
    ]
